# GlitchTip Infisical Configuration
# This file contains non-sensitive configuration details for Infisical integration
# Sensitive credentials are stored in gopass: infisical/machine-identities/hetzner-glitchtip-prod/*

infisical:
  project:
    name: glitchtip
    slug: glitchtip
    id: 215d0a7e-1320-4e25-91d3-a2dc540aa20a

  environment:
    name: prod
    slug: prod

  folders:
    root:
      id: bd2cf320-d7d7-49f2-8a33-0b7122f4ab0a
      path: /glitchtip
    database:
      id: f729d1f6-e94f-4de0-b4f8-d0a47155fa1f
      path: /glitchtip/database
    application:
      id: b9f54b93-2a85-4581-b5a9-6ca6c29823d8
      path: /glitchtip/application

  secrets:
    paths:
      database:
        path: /glitchtip/database
        folder_id: f729d1f6-e94f-4de0-b4f8-d0a47155fa1f
        secrets:
          - POSTGRES_PASSWORD: <32-char secure password>
      application:
        path: /glitchtip/application
        folder_id: b9f54b93-2a85-4581-b5a9-6ca6c29823d8
        secrets:
          - SECRET_KEY: <64-char Django secret key>
          - EMAIL_URL: smtp://glitchtip%40app:PASSWORD@smtp.postal.jefahnierocks.com:2525
          - DEFAULT_FROM_EMAIL: glitchtip@jefahnierocks.com

machine_identity:
  name: hetzner-glitchtip-prod
  identity_id: <TO_BE_CREATED>
  auth_method: Universal Auth
  role: viewer

  universal_auth:
    client_id: <TO_BE_CREATED>
    client_secret_description: hetzner-glitchtip-prod-secret
    # client_secret stored in: gopass show infisical/machine-identities/hetzner-glitchtip-prod/client-secret

  access:
    ttl: 7200  # 2 hours
    max_ttl: 86400  # 24 hours
    trusted_ips:
      - 91.99.101.204/32  # Hetzner server

  project_access:
    - project: glitchtip
      project_id: 215d0a7e-1320-4e25-91d3-a2dc540aa20a
      environment: prod
      role: viewer
      paths:
        - /glitchtip/database
        - /glitchtip/application

deployment:
  server:
    host: hetzner-secure
    ip: 91.99.101.204
    ssh_port: 2222
    user: verlyn13

  directories:
    compose: /opt/docker/glitchtip
    backups: /opt/backups/glitchtip
    scripts: /opt/scripts

  domain: glitchtip.jefahnierocks.com

  reverse_proxy:
    provider: traefik
    network: proxy
    cert_resolver: cloudflare

credentials_location:
  gopass:
    identity_id: infisical/machine-identities/hetzner-glitchtip-prod/identity-id
    client_id: infisical/machine-identities/hetzner-glitchtip-prod/client-id
    client_secret: infisical/machine-identities/hetzner-glitchtip-prod/client-secret

verification_commands:
  retrieve_identity_id: gopass show infisical/machine-identities/hetzner-glitchtip-prod/identity-id
  retrieve_client_id: gopass show infisical/machine-identities/hetzner-glitchtip-prod/client-id
  retrieve_client_secret: gopass show infisical/machine-identities/hetzner-glitchtip-prod/client-secret
  test_auth: |
    export INFISICAL_UNIVERSAL_AUTH_CLIENT_ID=$(gopass show infisical/machine-identities/hetzner-glitchtip-prod/client-id)
    export INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET=$(gopass show infisical/machine-identities/hetzner-glitchtip-prod/client-secret)
    infisical export --projectId=215d0a7e-1320-4e25-91d3-a2dc540aa20a --env=prod --path=/glitchtip

status:
  folders_created: ✅ Complete
  folders:
    - path: /glitchtip/database (f729d1f6-e94f-4de0-b4f8-d0a47155fa1f)
    - path: /glitchtip/application (b9f54b93-2a85-4581-b5a9-6ca6c29823d8)
  secrets_pending:
    - POSTGRES_PASSWORD (in /glitchtip/database)
    - SECRET_KEY (in /glitchtip/application)
    - EMAIL_URL (in /glitchtip/application)
    - DEFAULT_FROM_EMAIL (in /glitchtip/application)

notes:
  - Folder structure created successfully
  - Machine identity credentials to be created and stored in gopass
  - Identity should have viewer (read-only) access to glitchtip project
  - Restricted to Hetzner server IP only
  - Follows pattern established by Metabase and SonarQube deployments
  - Secrets need to be added via Infisical UI or CLI
